### ISSUE TITLE
4Dpop elements don't load

### ISSUE THREAD

**Issue by ezmac1964** [vdelachaux/4DPop#4]
I downloaded latest version of 4Dpop zip package v18r3 build 106 and opened with 4d 18r3 253822 only 4Dpop SVG is loaded.

**Comment by mesopelagique** [comment]
do we need to accept host database event to load 4d pop?

**Comment by vdelachaux** [comment]
https://discuss.4d.com/t/4d-pop-does-not-load/14466/14?u=vdl

**Comment by vdelachaux** [comment]
fixed
