### ISSUE TITLE
Common.xlf in ja.jproj raises XML parser error

### ISSUE THREAD

**Issue by miyako** [vdelachaux/4DPop#5]
```xml
          <source>A "&lt;" or "&gt;" was expected.</source>
          <target>“ < ”か“ > ”が必要です。</target>
```

**Comment by vdelachaux** [comment]
Hi Miyako
I don't find this resource into the 4DPop xliff files. Only into the file `~/4D.app/Contents/Resources/ja.lproj/Errors_4d_JA.xlf`
Could you give me more information ?
Thanks
Vincent

**Comment by miyako** [comment]
It has been some time since I used 4D Pop (it was for a customer, to reply to a discuss post) and reported this issue. At the time, I changed my system language to work around the issue. 

I do not remember clearly where I found the file...maybe "4DPop Macros", I am not sure. I think we can close this issue, due to incomplete information,
