### ISSUE TITLE
There are two typos in the documentation of at the end of: https://github.com/vdelachaux/4DPop

### ISSUE THREAD

**Issue by b-hal** [vdelachaux/4DPop#6]
Dear Vincent,
thank you for the great 4D Pop Macro declaration!
There are two typos in the documentation of at the end of: https://github.com/vdelachaux/4DPop
1. new line needet for 	COMPONENT LIST($tTxtComponents)
2. 4DPop_Palette not 4DPopPalette.

Best regards
Bernd

Working code for 4Dv19:

// Run 4DPop
// This code is available even if the component is not present like in the final application.
If (Not(Is compiled mode))
	ARRAY TEXT($tTxtComponents; 0)
	COMPONENT LIST($tTxtComponents)
	If (Find in array($tTxtComponents; "4DPop")>0)
		EXECUTE METHOD("4DPop_Palette")
	End if 
End if

**Comment by vdelachaux** [comment]
Thank you (Benoit?)
I made the correction
I'm glad that 4DPop can help you
