### ISSUE TITLE
4DPop (and related components)

### ISSUE THREAD

**Issue by truegold** [vdelachaux/4DPop#7]
Hi Vincent,

I have been trying to find 4D Pop and the XLIFF components that work with 4D v19r8. But the current ones are riddled with compiler errors because they expect 4D v20. The older ones haven't been updated by version since 2021. Apple OS 13.4.1 will not allow the older versions to be installed (only option trash) because of security issues.

Where do I get 4DPop (and related) components that will work with 4Dv19r8?

Thanks,
John...

**Comment by vdelachaux** [comment]
Hi John,
Are you using macOS? If yes, the 19R8.dmg is [here](https://github.com/vdelachaux/4DPop-Family)
Vincent

**Comment by truegold** [comment]
Hi Vincent,

Thank you! The link was on the overview page!

Appreciate,
John...

**Comment by truegold** [comment]
Hi Vincent,

Double-clicking and Apple says:

![ae](https://github.com/vdelachaux/4DPop/assets/25699211/b07bea30-f2c5-4df3-a477-e4ea6fb96bee)

Sigh,
John...

**Comment by vdelachaux** [comment]
Damn, I look

**Comment by truegold** [comment]
Hi Vincent,

So in order for this to work, the entire family of versions must be downloaded as a single zip. Then expand the zip and expand the dmg. That works. 

But not individually.

Appreciate,
John...

**Comment by vdelachaux** [comment]
No problem here...
On the main page, I clicked on the line 4DPop-Family-19R8.dmg
![Screenshot 8](https://github.com/vdelachaux/4DPop/assets/623020/6992cf28-09ae-4343-b593-98462793b4d6)

Then, at the top right of the open page, I clicked on the download icon.
![Screenshot 9](https://github.com/vdelachaux/4DPop/assets/623020/d40346e1-e53a-4601-b894-c3a7e270b8ba)

**Comment by truegold** [comment]
Hi Vincent,

Sorry to say it does expand but after copying them into an App's component folder and starting the app...

For each component, Apple says, it is damaged and cannot be opened...

I am confused?

John...

**Comment by vdelachaux** [comment]
Did you read and done as explained into the [main page](https://github.com/vdelachaux/4DPop-Family): "macOS user on ARM processor."?

**Comment by truegold** [comment]
Hi Vincent,

OK, so the components need to be installed in the version of 4D and opened within 4D first. Then they can be copied into the App folder I am working with.

Appreciate,
JOhn...

**Comment by truegold** [comment]
Hi Vincent,

That worked. I'll read the instructions first - next time.

Sorry for the distraction.
John...

**Comment by vdelachaux** [comment]
You are welcome
